In [195]:
import numpy as np

In [196]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(a)

In [197]:
np.mean(a)

5.0

In [198]:
type(a)

numpy.ndarray

In [199]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [200]:
my_matrix = np.array(my_matrix)

In [201]:
type(my_matrix)

numpy.ndarray

In [202]:
len(my_matrix)

3

In [203]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange
Return evenly spaced values with given interval

In [204]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [206]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [207]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## zeroes and ones
Generate arrays of zeroes or ones

In [208]:
np.zeros(3)

array([0., 0., 0.])

In [209]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [210]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [211]:
np. ones(5)

array([1., 1., 1., 1., 1.])

In [212]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [213]:
np.ones((3, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## linspace
Return overly spaced numbers over a specified interval

In [214]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [215]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye
Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [216]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random
Ways to create random arrays

In [217]:
np.random.rand(100)

array([0.04027506, 0.53603107, 0.97320785, 0.97521962, 0.10886878,
       0.89623371, 0.13456798, 0.18206426, 0.79776833, 0.87335577,
       0.30171328, 0.73872316, 0.43953806, 0.9363127 , 0.26309189,
       0.84111423, 0.13398665, 0.90266826, 0.32632276, 0.42049954,
       0.68074979, 0.79816163, 0.9187645 , 0.01952643, 0.40991388,
       0.06356101, 0.2399954 , 0.60973292, 0.11517535, 0.2006477 ,
       0.74846645, 0.11046737, 0.73908322, 0.48600655, 0.39288117,
       0.22202271, 0.01494122, 0.16380017, 0.97556579, 0.59105519,
       0.34279065, 0.62361362, 0.91643297, 0.74513973, 0.33980132,
       0.17374242, 0.90296334, 0.29726949, 0.6017692 , 0.73936199,
       0.01647152, 0.88866492, 0.29148858, 0.61403612, 0.05296535,
       0.48564308, 0.39050077, 0.95651684, 0.1917004 , 0.23965167,
       0.47188997, 0.97674631, 0.40278845, 0.96260429, 0.46376061,
       0.49278683, 0.60055596, 0.38896724, 0.14688801, 0.61611427,
       0.00999925, 0.58809268, 0.96200856, 0.63250704, 0.67984

## randn
Return a sample (or samples ) from the "Standard Normal" distribution, unlike rand wich is uniform

In [218]:
np.random.randn(5)

array([-1.10085172, -1.77507941, -0.01292062,  0.23495677, -1.41909603])

In [219]:
np.random.randn(5, 5)

array([[ 0.29414649,  0.42797101, -0.84298546, -0.51506891,  0.23248404],
       [-0.31792683, -0.59244647, -0.29792856, -0.38866122,  0.72069303],
       [-1.522699  ,  1.91013011,  0.54051829,  0.02964262, -0.31027939],
       [ 0.22382466,  1.92758203, -0.02210289, -0.61351919,  1.05466587],
       [-1.16974267,  0.93200074, -0.14235408, -1.969607  , -0.79790434]])

## randint
Return random integers from low(inclusive) to high(exclusive).

In [220]:
np.random.randint(1, 100)

71

In [221]:
np.random.randint(1, 100, 10)

array([78,  1, 82, 58, 48, 76, 67, 73, 86,  8])

## Array attributes and methods

In [222]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [223]:
len(arr)

25

In [224]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Reshape
Returns an array containing same data with a new shape

In [225]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [226]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [227]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

## max, min,argmax, argmin
These are useful for finding max or min values or to find their index locations using argmax or argmin

In [228]:
ranarr

array([ 8, 11, 29,  1, 44,  0, 30, 22, 24,  1])

In [229]:
ranarr.min()

0

In [230]:
ranarr.max()

44

In [231]:
ranarr.argmin()

5

In [232]:
ranarr.argmax()

4

In [233]:
new_ranarr = ranarr.reshape(5, 2)

In [234]:
new_ranarr

array([[ 8, 11],
       [29,  1],
       [44,  0],
       [30, 22],
       [24,  1]])

In [235]:
new_ranarr.min()

0

In [236]:
new_ranarr.argmin()

5

In [237]:
new_ranarr.max()

44

In [238]:
new_ranarr.argmax()

4

In [239]:
neg_ranarr = np.random.randint(-10, 10, (10, 2))
neg_ranarr

array([[ 7,  3],
       [-9,  2],
       [ 2,  5],
       [-2,  9],
       [ 7, -5],
       [ 5,  7],
       [ 2, -1],
       [ 6, -1],
       [ 7, -6],
       [ 1, -7]])

## Shape
Shows dimension of an array

In [240]:
neg_ranarr.shape

(10, 2)

## Arithmetic

In [241]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [242]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [243]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [244]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [245]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [246]:
arr1 = np.arange(11,20)

In [247]:
arr + arr1

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [248]:
arr - arr1

array([-10, -10, -10, -10, -10, -10, -10, -10, -10])

In [249]:
arr * arr1

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [250]:
arr / arr1

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421])

In [251]:
arr = arr.reshape(3,3)

In [252]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [253]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [254]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [255]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [256]:
arr1 = arr1.reshape(3,3)

In [257]:
arr + arr1

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [258]:
arr - arr1

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [259]:
arr * arr1

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [260]:
arr / arr1

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [261]:
arr**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [262]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [263]:
np.sin(arr1)

array([[-0.99999021, -0.53657292,  0.42016704],
       [ 0.99060736,  0.65028784, -0.28790332],
       [-0.96139749, -0.75098725,  0.14987721]])

In [264]:
np.cos(arr1)

array([[ 0.0044257 ,  0.84385396,  0.90744678],
       [ 0.13673722, -0.75968791, -0.95765948],
       [-0.27516334,  0.66031671,  0.98870462]])

In [265]:
np.tan(arr1)

array([[-2.25950846e+02, -6.35859929e-01,  4.63021133e-01],
       [ 7.24460662e+00, -8.55993401e-01,  3.00632242e-01],
       [ 3.49391565e+00, -1.13731371e+00,  1.51589471e-01]])

In [266]:
np.log(arr1)

array([[2.39789527, 2.48490665, 2.56494936],
       [2.63905733, 2.7080502 , 2.77258872],
       [2.83321334, 2.89037176, 2.94443898]])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to Python lists.

In [267]:
arr = np.random.randint(1, 10, 9)
arr

array([3, 7, 6, 5, 6, 4, 9, 1, 1])

In [268]:
# Get value at an index
arr[8]

1

In [269]:
arr[-1]

1

In [270]:
# Get values in range
arr[1:5]

array([7, 6, 5, 6])

## Broadcasting
Numpy differs from normal Python list because of their ability to broadcast

In [271]:
# Setting a value with index range (Broadcasting)
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   4,   9,   1,   1])

In [272]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   4])

In [273]:
arr_copy = arr.copy()
arr_copy

array([100, 100, 100, 100, 100,   4,   9,   1,   1])

## Indexing a 2D array (matrix)

In [274]:
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [275]:
# Indexing row
arr_2d[1]

array([20, 25, 30])

In [276]:
arr_2d[1][0]

20

In [277]:
arr_2d[1,0]

20

In [278]:
arr_2d[1:, 1:]

array([[25, 30],
       [40, 45]])

In [279]:
arr_2d[2]

array([35, 40, 45])

In [280]:
arr_2d[1:,0:2]

array([[20, 25],
       [35, 40]])